### ISSUE TITLE
Add back arm32 support after upstream fix

### ISSUE THREAD

**Issue by xoxys** [owncloud-docker/ubuntu#41]
Due to some broken arm32 support on Ubuntu upstream it was removed from our images as well. We should consider adding it back as soon as possible.

https://github.com/owncloud-docker/ubuntu/pull/38#issuecomment-634488622

**Comment by xoxys** [comment]
Related: https://github.com/owncloud-ci/php/pull/115

**Comment by jnweiger** [comment]
Re-checked via https://github.com/owncloud-docker/ubuntu/pull/43 - no luck today.

The docker.io/arm32v7/ubuntu:20.04 image cannot install wget. It fails with GPG-Errors on the http://ports.ubuntu.com/ubuntu-ports repositories.
IIRC, the original error was a permission denied related to libseccomp.
